### PR TITLE
Adding wallet on Whitelist-Testnet

### PR DESCRIPTION
**Pull request by AlexandreAutran**

### CODE REVIEW

**Comment by Boat0236** [comment]
0x9E010ad9312d8E4ea01bBE7f29DcEAb41Af8ed88

**Comment by BryleVillareal** [comment]
0x0a1032d686bfc24e9fcc5e728481884bc45e297a

**Comment by KrisKsa** [comment]
0x1682db78a752c660B31bc185EF0C4E221Bb93f36

**Comment by Mity80** [comment]
0x14B47e650DcdA3Faf7C7dccB19A8c99883B3408D

**Comment by peejabh** [comment]
0x19D9314E64B7bd5CF9a053141905487ae1541851

**Comment by Bazavan1** [comment]
0xDeba10d151D2f9F3B70f7D9393631E60db282cB6

**Comment by ZikaRei** [comment]
0x14957a223cBE29E9fC96B1b2C6e2f96a4D72a8B7

**Comment by Jukid0** [comment]
0x9Ded376789dA87642e55F8dBBF72f1bf25D909A3

**Comment by BalboaBR** [comment]
0x199Eb1fC96C99aDB32cF3757a402d079D9A60AF2

**Pull request closed without merging**
